# print('welcome home')                                       
# a=3
# b=2
# c=7.2
# print(type(a))
# print(type(b))
# print(a,type(a),b,type(b))
# print(type(c))
# print(a,type(a),c,type(c),b,type(b))
#  print('%d'%a)
# print('%i'%b)
# print('%d'' is my value'%a),print('%d'' is my value'%b) 
# print('%d'' is my value'%a,'%i'' is my value'%b )    
# print('%f'%a,'%f'%b)
# print('%.2f'%a)
# print('%.7f'%b)
# print('%.nf'%a)       
# c=None
# print(c,type(c))
# r="None"
# print(r,type(r))
# print('iam enjoying my class\
# because im intersted in this class')
# print('hi\amazon')
# print('hi\\amazon')
# print('baby\barbie')
# print('baby\\barbie')
# print('have\fun')
# print('have\\fun')
# print('great\news')
# print('great\\news')
# print('great\News')
# print('great\\News')
# print('interviwe\round')
# print('interview\\round')
# print('hello\ttapsi')
# print('hello   tapsi')
# print('hello\\tapsi')
# print('\thello tapsi')
# print('        hello tapsi')
# print('\u0001')
# print('\u0002♦')
# print('\u0003')
# print('\u0004')
# print('\u0005')
# print('\u0006')
# print('\u0007')
# print('\u0008')
# print('\u0009')
# print('hello\Users')
# print('hello\\Users')
# print('c:\Users\New\Josh\Hd')
# print('c:\\Users\\New\\Josh\\Hd')
# print('hello\vaishnavi')
# print('hello\\vaishnavi')

# print(a.isspace())
# print(b.isspace())
# print(c.isspace())
# print(d.isspace())
# c=5
# print("hi",c)
# print('hi'+' '+str(c))
# b=3.10
# print('python verison used is',b)
# print('python version used is %f'%b)
# print('python verison used is'+str(b))

# a='5';b=4;c=8;d='3'
# print(a+d)
# print('sushma\n'*1000)
# print("helllo0\rse")
s='python'
# print(s[ :4 : ])
# print(s[0: :1])
# print(s[1: :2])
# print(s[2:3: ])
# print(s[0:5:2])
# print(s[ : :-1])
# print(s[-1: :-5])
# print(s[-1: :-2])
# print(s[0: :-1])
# print(s[ : :1])
# print(s[ : :2])
# print(s[ : :3])
# print(s[ : :4])
# print(s[ : :5])
# print(s[ : :6])
# print(s[ : :-1])
# print(s[ : :-2])
# print(s[ : :-3])
# print(s[ : :-4])
# print(s[ : :-5])
# print(s[ : :-6])
# print(s[  : :-7])
# print(s[-1: : ])
# print(s[-2: : ])
# print(s[-3: : ])
# print(s[-4: : ])
# print(s[-5: : ])
# print(s[-6: : ])
# print(s[-7: : ])
# print(s[-8: : ])

# print("bablu"[ : :-1])
s="hello python programing "
# print(s.capitalize())
# print(s.casefold())
# print(s.title())
# print(s.isupper())
# print(s.islower())
# print(s.center( 25,'*'))
# print(len(s))
# print(s.endswith())
# print(s.endswith(''))
# print(s.endswith(' '))
# print(s.endswith('g'))
s=s.encode()
print(s)
print(s.decode())
print(type(b'hello'))


